#!/opt/tapper/bin/perl

use Tapper::TestSuite::HWTrack;
use Log::Log4perl;

my $string = "
log4perl.rootLogger                               = INFO, root
log4perl.appender.root                            = Log::Log4perl::Appender::Screen
log4perl.appender.root.layout                     = SimpleLayout";
Log::Log4perl->init(\$string);

eval {
        my $track  = Tapper::TestSuite::HWTrack->new;
        $report = $track->generate();
        $track->send($report);
};

exit 0;
